mindmap
  root((Utility tree для системы запроса документов по бухгалтерским операциям))
    Performance & Latency
      p95 ключевых операций ≤ 1 сек
      p95 создания сбора ≤ 30 сек
      p95 загрузки документа ≤ 5 сек
    Availability & Reliability
      Доступность услуги по запросу документов ≥ 98.5%
      Доступность услуги по загрузке и скачиванию документов ≥ 99,9%
      MTTR ≤ 30 мин
    Security & Privacy
      100% клиентских операций с авторизацией
      100% межсервисных операций с авторизацией
      TLS 1.3+ шифрование
      Валидация при загрузке для 100% разрешенных типов документов
        Валидация вложенных файлов в архивах по тем же правилам
    Observability & Monitoring
      Логирование и трассировка 100% критичных операций
      Мониторинг 100% внешних интеграций
    Data Quality & Consistency
      Кол-во утерянных записей при поставке в DWH ≤ 0.1%
    Usability
      Обработка документов после загрузки клиентом ≤ 48ч для 95%